language: node_js
node_js:
  - "node"
branches:
  only:
  - master
before_install:
- npm install -g hexo
- npm install
install:
- gulp scss
- hexo generate
- gulp beautify
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "hisaac.net"
  skip_cleanup: true
  local_dir: public
  cache_control: "max-age=21600"
after_deploy:
  # Allow `awscli` to make requests to CloudFront.
  - aws configure set preview.cloudfront true
  # Invalidate every object in the targeted distribution.
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
