language: node_js
node_js:
  - "node"
branches:
  only:
  - master
before_install:
- npm install -g hexo
- npm install
install:
- gulp scss
- hexo generate
- gulp beautify
deploy:
  provider: s3
  access_key_id: AWS_ACCESS_KEY
  secret_access_key: AWS_SECRET_KEY
  bucket: "hisaac.net"
  skip_cleanup: true
