title: hisaac.net
email: hello@hisaac.net
description: Isaac Halvorson's home on the web
url: "https://hisaac.net"
twitter_username: hisaac
github_username: hisaac

exclude:
  - old
  - site-archive

# Build settings
theme: minima
plugins:
  - jekyll-feed
