title: hisaac.net
email: hello@hisaac.net
description: Isaac Halvorson's home on the web
url: "https://hisaac.net"
twitter_username: hisaac
github_username: hisaac

author:
  name: Isaac Halvorson
  email: hello@hisaac.net

permalink: /:year/:month/:day/:title.html

include:
  - .well-known

exclude:
  - CHANGELOG*
  - Gemfile*
  - LICENSE*
  - old
  - README*
  - site-archive

defaults:
  - scope:
      path: '_posts'
      type: 'posts'
    values:
      layout: 'post'
      author: Isaac Halvorson

jekyll_tidy:
  exclude:
    - .well-known/humans.txt
    - .well-known/robots.txt
