baseURL			= "https://hisaac.net/"
languageCode	= "en-us"
title			= "hisaac.net"

uglyurls = true
pygmentsCodefences = true

[params]
	Title = "hisaac.net"
	SiteDescription = "The personal webpage and weblog of Isaac Halvorson"
	author = "Isaac Halvorson"
	twitter = "hisaac"
	email = "hello@hisaac.net"

[permalinks]
	posts = "/:year/:month/:day/:title/"
